version: 2.1

executors:
  gradle:
    docker:
      - image: cimg/openjdk:11.0
  helm:
    docker:
      - image: hypertraceorg/helm-gcs-packager:0.1.0

commands:
  gradle:
    description: "Run the provided gradle command"
    parameters:
      args:
        type: string
      when:
        default: "on_success"
        type: enum
        enum: ["on_fail", "on_success", "always"]
    steps:
      - run:
          name: << parameters.args >>
          command: ./gradlew << parameters.args >> --info
          when: << parameters.when >>

jobs:
  tag:
    executor: gradle
    steps:
      - checkout
      - gradle:
          args: :tag -Prelease
      - add_ssh_keys:
          fingerprints:
            - "4d:62:7a:9d:d7:e4:d7:55:5a:e8:bc:69:29:0c:ae:0b"
      - run: git push origin $(./gradlew -q :printVersion)
  validate-charts:
    executor: helm
    steps:
      - checkout
      - run:
          name: Helm Charts Lint and Template Render
          command: |
            helm lint --strict ./helm/ -f src/test/resources/values.yaml
            helm template --dry-run ./helm/ -f src/test/resources/values.yaml
  package-charts:
    executor: helm
    steps:
      - checkout
      - run:
          name: Package and Publish Helm Charts
          # Read the "name:" from Chart.yaml. The chart version is <chart-name>-<semver git tag>
          command: |
            CHART_VERSION=$(git describe --abbrev=0)
            CHART_NAME=$(awk '/^name:/ {print $2}' ./helm/Chart.yaml)
            export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/helm-gcs-key.json
            echo ${HELM_GCS_CREDENTIALS} > ${GOOGLE_APPLICATION_CREDENTIALS}
            helm repo add helm-gcs ${HELM_GCS_REPOSITORY}
            helm package --version ${CHART_VERSION} --app-version ${CHART_VERSION} ./helm/
            helm gcs push ${CHART_NAME}-${CHART_VERSION}.tgz helm-gcs --public --retry

workflows:
  version: 2
  validate-and-publish:
    jobs:
      - validate-charts
      - tag:
          context: hypertrace-publishing
          requires:
            - validate-charts
          filters:
            branches:
              only:
                - master
      - package-charts:
          context: hypertrace-publishing
          requires:
            - tag
          filters:
            branches:
              only:
                - master
